const SET_QUERY = "SET_QUERY";
const SET_DATA = "SET_DATA";
const SET_LOADING = "SET_LOADING";
const CHANGE_NEXT_PAGE = "CHANGE_NEXT_PAGE";
const CHANGE_PREV_PAGE = "CHANGE_PREV_PAGE";
const REMOVE_STORY = 'REMOVE_STORY'

export { SET_QUERY, SET_DATA, SET_LOADING, CHANGE_NEXT_PAGE, CHANGE_PREV_PAGE, REMOVE_STORY };
